
services:
  website:
    build: .
    restart: unless-stopped
    ports:
      - "5001:80"  # Changed: map external 5001 to internal 80
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./logos.svg:/usr/share/nginx/html/logos.svg
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=web'
      - 'traefik.http.routers.portfolio.rule=Host(`lukejameson.gg`)'
      - 'traefik.http.routers.portfolio.entrypoints=websecure'
      - 'traefik.http.routers.portfolio.tls.certresolver=letsencrypt'
      - 'traefik.http.services.portfolio.loadbalancer.server.port=80'
      - 'traefik.http.middlewares.security-headers.headers.frameDeny=true'
      - 'traefik.http.middlewares.security-headers.headers.sslRedirect=true'
      - 'traefik.http.middlewares.security-headers.headers.browserXssFilter=true'
      - 'traefik.http.routers.portfolio.middlewares=security-headers@docker'
    networks:
      - web
networks:
  web:
    external: true